### ISSUE TITLE
Non-SSO Auth option

### ISSUE THREAD

**Issue by svenlito** [ljacobsson/evb-cli#26]
Running into an issue where SSO isn't available on the AWS account I'm working with. 
Would you consider adding a non-SSO auth variant, please?

**Comment by ljacobsson** [comment]
Thanks for reporting. Will look in to this asap!

**Comment by ljacobsson** [comment]
@svenlito 

Can you please try if v1.1.36 fixes this for you?

Working with the AWS credentials chain is a nightmare

**Comment by svenlito** [comment]
> Can you please try if v1.1.36 fixes this for you?

it does

> Working with the AWS credentials chain is a nightmare

Can be at times, indeed :)

Thank you!

**Comment by ljacobsson** [comment]
Nice!

Thanks again for reporting :+1:
