### ISSUE TITLE
Self Signed Cert

### ISSUE THREAD

**Issue by stephenbawks** [ljacobsson/evb-cli#4]
Is there a way to use a self-signed certificate?  Not sure if there is an environment variable that can be specified?

(node:13688) UnhandledPromiseRejectionWarning: Error: self signed certificate in certificate chain

**Comment by stephenbawks** [comment]
Actually looks like i need to add an environment variable named
NODE_EXTRA_CA_CERTS
 
That then points to the local of the PEM File
path/to/certificate.pem

**Comment by stefan-karlsson** [comment]
Did you manage to solve this @stephenbawks ?

**Comment by stephenbawks** [comment]
> Did you manage to solve this @stephenbawks ?

Yeah the solution I had is working.
