### ISSUE TITLE
Add ability to test an event payload against rules on a specific bus

### ISSUE THREAD

**Issue by nmoutschen** [ljacobsson/evb-cli#8]
As a user of the evb-cli, I'd like to test if an event matches the EventBridge rules on a bus, which would help debugging rules and see if they match my expectations.

This would take an event as input, query the list of rules for that bus, retrieve the pattern for each rule, and check the event against each pattern. This should have the option to select the rule name.

This could have a simplified view showing just each rule with a checkmark, or a detailed view where I can see which section of the pattern matches the rule or not.

**Comment by ljacobsson** [comment]
Thanks for raising! 

This is a very good addition!

**Comment by ljacobsson** [comment]
Fixed in v1.1.6.

Closing
